name: pointtrackernew
description: A new Flutter application.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  sqflite:
  path_provider:
  google_fonts:
  fab_circular_menu:


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

 